### ISSUE TITLE
Inner devDependency vargs missing from npm

### ISSUE THREAD

**Issue by danyshaanan** [flatiron/flatiron#117]
...breaking `npm i`.

this > https://www.npmjs.com/package/resourceful > https://www.npmjs.com/package/cradle > https://www.npmjs.com/package/vargs which has disappeared from npmjs.

More info here: https://github.com/admc/wd/issues/400

**Comment by 3rd-Eden** [comment]
That should probably be reported at https://github.com/cloudhead/vargs instead.

**Comment by danyshaanan** [comment]
@3rd-Eden I did that, just thought you'd want to know that flatiron is broken for dev and why.

**Comment by 3rd-Eden** [comment]
@danyshaanan We're already aware of it, but the core of the problem is caused by npm as the package it self has not been unpublished so ultimately they are the folks that need to fix and resolve these issues. 

As a temp work around you could use 

```
npm install vargs --registry https://registry.nodejitsu.com
```

to install the module until npm get's their stuff together.

**Comment by danyshaanan** [comment]
Seems vargs has reappeared.
